spring:
  application:
    name: '@project.artifactId@'
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: var/git-repo
            order: 2
        bootstrap: true
  security:
    user:
      name: kyleus

server:
  port: 8088
