###YAML

// @no-cookie-jar
GET {{protocol}}{{KAL_ENV_CS_USERNAME}}:{{KAL_ENV_CS_PWD}}@{{configServer}}/thelab/dev

###OTHER TEST
// @no-cookie-jar
GET {{protocol}}{{KAL_ENV_CS_USERNAME}}:{{KAL_ENV_CS_PWD}}@{{configServer}}/thelab/PROD


###NO JAVA TEST
// @no-cookie-jar
GET {{protocol}}{{KAL_ENV_CS_USERNAME}}:{{KAL_ENV_CS_PWD}}@{{configServer}}/thelab-DEV.json?resolvePlaceholders=true


